userInput[0] == lotteryNumber[0]
            || userInput[0] == lotteryNumber[1]
            || userInput[0] == lotteryNumber[2]
            || userInput[1] == lotteryNumber[0]
            || userInput[1] == lotteryNumber[1]
            || userInput[1] == lotteryNumber[2]
            || userInput[2] == lotteryNumber[0]
            || userInput[2] == lotteryNumber[1]
            || userInput[2] == lotteryNumber[2]